#!/usr/bin/env bash
#
# General functions used for installs and updates
#
###############################################################################

# color output
cNo=`tput sgr0`
cRed=`tput setaf 1`
cGreen=`tput setaf 2`
cYellow=`tput setaf 3`
cBlue=`tput setaf 4`
cMagenta=`tput setaf 5`
cCyan=`tput setaf 6`
cWhite=`tput setaf 7`

inArray () {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

# prints a header block
print_block () {
  local i="$1" ; size=${#i}
  ((size+=2))
  printf "\n$cCyan"
  printf "%0.s*" $(seq 1 $size)
  printf "\n $cBlue$1\n$cCyan"
  printf "%0.s*" $(seq 1 $size)
  printf "$cNo\n\n"
}

# print rainbows and unicorns
print_fancy () {
  local font=${2}
  printf "$cGreen"
  figlet -f ${font:=$(printf "small")} ${1}
  printf "$cNo\n"
}

# prints a closing block
print_block_end () {
  if [ ! -z "$1" ];then
    printf "\n$cBlue$1\n"
  fi
  printf "\n$cCyan"
  printf "%0.s*" $(seq 1 $size)
  printf "$cNo\n"
}

# pretty line output
print_line () {
  printf "$1$cGreen $2$cNo$3\n"
}

# pretty warning
print_warning () {
  printf "\n${cRed}Warning: ${cYellow}${1}${cNo}\n"
}

# print task header
print_task () {
  printf "\n$1 $cGreen$2$cNo\n"
}

# pretty error output
print_error () {
  printf "$cRed$1 $cYellow$2$cNo\n"
}

# check if a command exists
command_exists () {
  type "$1" &> /dev/null ;
}

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

uncomment () {
  sudo sed -ie "s|#${1}|${1}|g" "$2"
}

# outputs debug if $verbose is truthy
verboseOut () {
  if [ "$verbose" = true ]; then
    echo $1 $cYellow$2 $cNo
  fi
}
