#!/usr/bin/env bash
#
# General functions used for installs and updates
#
###############################################################################

# color output
cNo=`tput sgr0`
cRed=`tput setaf 1`
cGreen=`tput setaf 2`
cYellow=`tput setaf 3`
cBlue=`tput setaf 4`
cMagenta=`tput setaf 5`
cCyan=`tput setaf 6`
cWhite=`tput setaf 7`

inArray () {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}


info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}
