#!/usr/bin/env bash
#
# Update all the things

set -e

# Include the general functions
. $DOTFILES/functions/general

print_block "Updating All The Things"
print_line "Making sure we're up-to-date first..."

cd $DOTFILES && git up

cd "$(dirname $0)"/..

# find the update.sh files and run them iteratively
find . -name update.sh -not -path "./vendor/*" | while read updater ; do sh -c "${updater}" ; done
