name: Dotfiles Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Bats and bats libs
         id: setup-bats
         uses: bats-core/bats-action@3.0.0
      - run: sh src/script/test
